version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432

  web: 
    image: rocksolid
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 4000:3000
