name: 🐛 Bug
description: Vertel me over een fout in de applicatie
title: "[BUG] <titel>"
labels: [bug]
body:
- type: input
  id: url
  attributes:
    label: URL
    description: Copy en paste de URL hier
    placeholder: https://acc-rock-solid-web-app.azurewebsites.net/cursussen/101/edit/
  validations:
    required: false
- type: textarea
  attributes:
    label: Dit gebeurt er nu
    description: Beschrijf wat er nu gebeurt.
  validations:
    required: false
- type: textarea
  attributes:
    label: Dit had ik verwacht
    description: Beschrijf wat je had verwacht dat er zou gebeuren.
  validations:
    required: false
- type: textarea
  attributes:
    label: Wat wil je me nog meer vertellen?
    description: |
      Achtergrond informatie, screenshots, etc.
  validations:
    required: false
