name: Deploy

on: [workflow_dispatch]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Acceptance
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: npm ci
    - run: npm run deploy:acc
      env:
        AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
        AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
