name: mutation testing

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "test/add-stryker"
      
jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: cp .env.template .env
    - name: '👽 Run Stryker'
      run: npm run test:mutation
      env:
        STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

